spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/modsen_library
    username: postgres
    password: 12345678
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
        alphanumeric-ids:
          enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

  server:
    port: 8080
