spring:
  datasource:
    url: jdbc:postgresql://postgres-books:5433/modsen_library
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://library-server:8761/eureka/